--- # ---------------------------------------------------------------------------
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: tfbc.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Buyer
  # ---------------------------------------------------------------------------
  - Name: Buyer
    Domain: buyer.tfbc.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Seller
  # ---------------------------------------------------------------------------
  - Name: Seller
    Domain: seller.tfbc.com
    Template:
      Count: 1
    Users:
      Count: 1

 # ---------------------------------------------------------------------------
  # Seller Bank
  # ---------------------------------------------------------------------------
  - Name: SellerBank
    Domain: sellerbank.tfbc.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Buyer Bank
  # ---------------------------------------------------------------------------
  - Name: BuyerBank
    Domain: buyerbank.tfbc.com
    Template:
      Count: 1
    Users:
      Count: 1

 # ---------------------------------------------------------------------------
  # Carrier
  # ---------------------------------------------------------------------------
  - Name: Carrier
    Domain: carrier.tfbc.com
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
